### PR TITLE
Minor improvements to 68 beta notes

### PR DESCRIPTION
**Pull request by darktrojan**

### CODE REVIEW

**Comment by wsmwk** [comment]
Perhaps you sought to tone down or add clarity to the "current" wording (which is a revision of Jorg's original draft), but this proposed revision I think is worse  "Various UI improvements. Many changes affecting UI, and so problems are not unexpected.    Please file bug reports at [bugzilla.mozilla.org](https://bugzilla.mozilla.org/)."  

The point of the current wording is to specifically ask users users to look for potential problems, because of the extensive backend changes in XUL and XBL.  We should expect problems, and we very much want them to be addressed quickly so they are fixed before final release. A possible simplified revision is something like

Many visible and not visible UI changes.  Please file bug reports for all issues at [bugzilla.mozilla.org](https://bugzilla.mozilla.org/).

**Comment by darktrojan** [comment]
I'm not really fussed about that change, I just thought it looked weird.

**Comment by wsmwk** [comment]
Sorry Geoff, actually I misread your proposed revision - I missed the "un" of "not unexpected".  But the double negative is problematic.

@jorgk3 - does my last proposed wording above work for you?

**Comment by jorgk3** [comment]
Sorry, I don't follow GitHub much. Is there sill an issue?

**Pull request closed without merging**
